---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-blockchain-node-1
  labels:
    app: go-blockchain-node-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-blockchain-node-1
  template:
    metadata:
      labels:
        app: go-blockchain-node-1
    spec:
      containers:
      - name: go-blockchain-node-1
        image: quiquell/go-blockchain:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-blockchain-node-2
  labels:
    app: go-blockchain-node-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-blockchain-node-2
  template:
    metadata:
      labels:
        app: go-blockchain-node-2
    spec:
      containers:
      - name: go-blockchain-node-2
        image: quiquell/go-blockchain:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-blockchain-node-3
  labels:
    app: go-blockchain-node-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-blockchain-node-3
  template:
    metadata:
      labels:
        app: go-blockchain-node-3
    spec:
      containers:
      - name: go-blockchain-node-3
        image: quiquell/go-blockchain:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: go-blockchain-node-1
  labels:
    app: go-blockchain-node-1
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: go-blockchain-node-1
---
apiVersion: v1
kind: Service
metadata:
  name: go-blockchain-node-2
  labels:
    app: go-blockchain-node-2
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: go-blockchain-node-2
---
apiVersion: v1
kind: Service
metadata:
  name: go-blockchain-node-3
  labels:
    app: go-blockchain-node-3
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: go-blockchain-node-3
